nosana:
  description: "Template Repo Pipeline Validate"

global:
  image: registry.hub.docker.com/library/node:18

  trigger:
    branch:
      - pipeline

  allow_failure: false

jobs:
  - name: Install Dependencies
    commands:
      - npm ci
      - ls -lah
    artifacts:
      - name: node_modules
        path: ./node_modules

  - name: yaml lint
    image: pipelinecomponents/yamllint
    commands:
      - yamllint templates/*/template.yml

  - name: Run Validator Script
    commands:
      - ls -lah
      - npm run validate_all
    resources:
      - name: node_modules
        path: ./
