nosana:
  description: "Template Repo Pipeline Validate"

global:
  image: node:18
  trigger:
    branch:
      - main

jobs:
  - name: Install Dependencies
    commands:
      - npm ci
    artifacts:
      - name: node_modules
        path: ./node_modules

  - name: yaml lint
    image: pipelinecomponents/yamllint
    commands:
      - yamllint --format colored .

  - name: Run Validator Script
    commands:
      - npm run validate_all
    resources:
      - name: node_modules
        path: ./
