nosana:
  description: "Template Repo Pipeline Validate"

global:
  image: registry.hub.docker.com/library/node:18

  trigger:
    branch:
      - pipeline
      
  environment:
    TERM: xterm-color
    FORCE_COLOR: "1"
    CLICOLOR: "1"
    CLICOLOR_FORCE: "1"

  allow_failure: false

jobs:
  - name: Install Dependencies
    commands:
      - npm ci
      - ls -lah
    artifacts:
      - name: node_modules
        path: ./node_modules

  - name: yaml lint
    image: registry.hub.docker.com/pipelinecomponents/yamllint
    commands:
      - yamllint .

  - name: Run Validator Script
    commands:
      - ls -lah
      - npm run validate_all
    resources:
      - name: node_modules
        path: ./
