repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
        files: ^templates/
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0 # https://github.com/adrienverge/yamllint/tags
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
