repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
        files: ^templates/
  - repo: local
    hooks:
      - id: schema-validator
        name: Nosana schema validator
        entry: npm run validate
        language: system
        pass_filenames: false
