nosana:
  description: Nosana x Squads Deployment

global:
  image: nosana/solana:v1.0.5

  environment:
    # testnet / devnet / mainnet / <your-custom-sol-rpc>
    SOLANA_URL: devnet
    AUTHORITY_PUBKEY: <Your-PubKey-Here>
    MULTISIG_PUBKEY: <Your-PubKey-Here>
    SQUADS_PUBKEY: <Your-PubKey-Here>

  trigger:
    branch:
      - master

jobs:
  - name: build program
    commands:
      - npm run build:program-rust
    artifacts:
      - name: program
        path: dist/program/helloworld.so

  - name: write buffer
    secrets:
      SOLANA_WALLET
    commands:
      - mkdir solana
      - echo $SOLANA_WALLET > solana/private-key.json
      - solana config set --url devnet --keypair solana/private-key.json
      - solana address > solana/spill.txt
      - solana program write-buffer /helloworld.so | tee solana/buffer.txt
      - |
        solana program set-buffer-authority \
        "$(cut -d ' ' -f2 < solana/buffer.txt)" \
        --new-buffer-authority $AUTHORITY_PUBKEY
    resources:
      - name: program
        path: /
    artifacts:
      - name: solana
        path: solana

  - name: squads deploy
    commands:
      - |
        nosana-cli create-program-upgrade                        \
          --name        upgradeTest                              \
          --private-key /solana/private-key.json                 \
          --buffer      "$(cut -d ' ' -f2 < /solana/buffer.txt)" \
          --spill       "$(cat /solana/spill.txt)"               \
          --multisig    $MULTISIG_PUBKEY                         \
          --program     $SQUADS_PUBKEY                           \
          --authority   $AUTHORITY_PUBKEY
    resources:
      - name: solana
