global:
  image: projectserum/build:v0.27.0
  environment:
    SOLANA_URL: mainnet-beta # testnet / devnet / mainnet / your-custom-sol-rpc
    PROGRAM_ID: <Your-PubKey-Here>
    PRIVATE_KEY_PATH: /root/.config/solana/id.json
    SQUADS_AUTHORITY_PUBKEY: <Your-PubKey-Here>
    SQUADS_MULTISIG_PUBKEY: <Your-PubKey-Here>
    SQUADS_PROGRAM_PUBKEY: <Your-PubKey-Here>

  # Trigger pipeline on these branches:
  trigger:
    push:
      branches: '*'

jobs:
  - name: build
    commands:
      - anchor build
    artifacts:
      - name: programs
        path: target

# Uncomment this if you want to add anchor test step
#  - name: test
#    secrets:
#      - TEST_KEY
#    commands:
#      - echo "${TEST_KEY}" > "${PRIVATE_KEY_PATH}"
#      - npm ci
#      - anchor test
#    resources:
#      - name: programs
#        path: .

  - name: deliver
    image: nosana/solana:v1.0.16
    secrets:
      - SQUADS_KEY
    commands:
      - solana config set --url "${SOLANA_URL}"
      - REMOTE_HASH="$(solana-verify get-program-hash "${PROGRAM_ID}")"
      - echo "On chain hash is ${REMOTE_HASH}"
      - LOCAL_HASH="$(solana-verify get-executable-hash "target/deploy/${PROGRAM_NAME}.so")"
      - echo "Compiled hash is ${LOCAL_HASH}"
      - |
        if [ "${REMOTE_HASH}" = "${LOCAL_HASH}" ]
        then
          echo Programs are equal, deployment cancelled
          exit 0
        else
          echo Continue deployment
        fi
      - echo "${SQUADS_KEY}" > "${PRIVATE_KEY_PATH}"
      - BUFFER_ACCOUNT="$(solana program write-buffer "target/deploy/${PROGRAM_NAME}.so" | cut -d ' ' -f2)"
      - if [ -z "${BUFFER_ACCOUNT}" ]; then exit 1; else echo "Buffer account is ${BUFFER_ACCOUNT}"; fi
      - solana program set-buffer-authority "${BUFFER_ACCOUNT}" --new-buffer-authority "${SQUADS_AUTHORITY_PUBKEY}"
      - |
        nosana-cli create-program-upgrade            \
          --name        upgradeProgram               \
          --private-key "${PRIVATE_KEY_PATH}"        \
          --buffer      "${BUFFER_ACCOUNT}"          \
          --spill       "$(solana address)"          \
          --network     "${SOLANA_URL}"              \
          --multisig    "${SQUADS_MULTISIG_PUBKEY}"  \
          --program     "${SQUADS_PROGRAM_PUBKEY}"   \
          --authority   "${SQUADS_AUTHORITY_PUBKEY}" \
          --approve
    resources:
      - name: programs
        path: .
